# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[dev.deploy.parameters]
stack_name = "sam-sample-app-dev"
s3_bucket = "sam-sample-app-deployment-bucket-dev"
s3_prefix = "dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev DBHost=dev-db.example.com APIKey=dev-api-key Stage=dev TABLE_NAME=items-dev"

[qa.deploy.parameters]
stack_name = "sam-sample-app-qa"
s3_bucket = "sam-sample-app-deployment-bucket-qa"
s3_prefix = "sam-sample-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=qa DBHost=qa-db.example.com APIKey=qa-api-key TABLE_NAME=items-qa"

[default.global.parameters]
stack_name = "sam-test-app-3"

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
